### ISSUE TITLE
[Roadmap] Frontend Framework 

### ISSUE THREAD

**Issue by TheCodedOne** [Diluv/MMD-Client#3]
A front end framework to use on the launcher

The ones i know of are;

- AngularJS
- AngularJS 2
- ReactJS

**Comment by trentv4** [comment]
I don't have any preference or beef in this fight, but I will always suggest eeking out performance where you can. Front-end frameworks can be helpful, but they can also be a bit heavy and performance-demanding, esp. on low end machines. It's possible to write interfaces using regular DOM functions and that should also be a contestant

**Comment by JamiesWhiteShirt** [comment]
We need to be able to develop things efficiently, elegantly and with possibility of code reuse, so I consider vanilla HTML/CSS/javascript to be out of the question.

Angular 2 and ReactJS definitely has the performance we need. Angular 2 uses TypeScript, which means we probably should too for either good or bad.

I personally would prefer React, mainly because I am already familiar with it and what little Angular 2 I have tried didn't impress me as much as React.

**Comment by JamiesWhiteShirt** [comment]
Also, keep in mind that whatever decision we make here should also be reflected for the web client.
