### ISSUE TITLE
[Roadmap] Distribution

### ISSUE THREAD

**Issue by TheCodedOne** [Diluv/MMD-Client#4]
How we will distribute the client on windows, mac and linux and have updating

**Comment by trentv4** [comment]
Could you elaborate what you mean?

**Comment by TheCodedOne** [comment]
Like what system we'll use to update the client and create the .exe/.dmg/.whatever files

**Comment by trentv4** [comment]
Electron has distribution and packaging tutorials available:

https://github.com/electron/electron/blob/master/docs/tutorial/application-distribution.md
https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md

I would recommend going with packing asar files instead of shipping with loose files.

**Comment by TheCodedOne** [comment]
theres also squirrel which is a possibility and that handles updates too https://github.com/Squirrel
