### ISSUE TITLE
[Roadmap] UI Design

### ISSUE THREAD

**Issue by TheCodedOne** [Diluv/MMD-Client#5]
Need to work out how we want it to look

**Comment by trentv4** [comment]
I sketched a handful of designs that could work: https://i.imgur.com/2hNuDWe.png . I would advise going for one that has a sidebar, because most people have widescreens and there's more horizontal room on the screen than vertical. 

For color scheme, the only major color of MMD I can identify is the green gradient of the MMD logo featured prominently here: https://mcmoddev.com/members/, and the grey and black featured on that page.

**Comment by TheCodedOne** [comment]
Gonna pop in my april fools joke as possible design ideas ![3](https://cloud.githubusercontent.com/assets/17037059/24654211/ac91e1ee-1930-11e7-989a-34fa0b990e96.png)

**Comment by TheCodedOne** [comment]
Personally i like the idea of a small sidebar but that extends out when you hover over it

**Comment by trentv4** [comment]
On the Spotify client, there used to be a ">>" button which expanded and collapsed the sidebar between a large sidebar with text vs small sidebar of icons only. That would be superior to causing the sidebar to dynamically change as you hover over it, imo

**Comment by TheCodedOne** [comment]
Probably aye
